### ISSUE TITLE
Verification requirement with relational expression fails

### ISSUE THREAD

**Issue by eltazar86** [STARIONGROUP/COMET-IME-Community-Edition#1252]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We have a requirement with a parameter constraint with AND operator in order to have a parameter between two values.
We have linked the requirement to the parameter through the function "Create a binary relationship"
When we try to verify the requirements, this requirement is yellow (does it means that the link does not work?)

 
### System Configuration

- COMET version:
  - [X] COMET-IME: 9.4.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
please make use of the drag-n-drop capability to drop a parameter on a parametric constrating to create the relationship, that should work. @lxatrhea do you agree this is the approach?

**Comment by lxatrhea** [comment]
> please make use of the drag-n-drop capability to drop a parameter on a parametric constrating to create the relationship, that should work. @lxatrhea do you agree this is the approach?

@samatrhea That is indeed the easiest way.
I think the problem here is that in the BinaryRelationship the parameter should reference both RelationalExpressions that are part of the AND operator.
When you drag and drop you will see that you cannot even drop a parameter on a requirement, only on RelationExpressions.

Explanation of this is that in theory a single requirement might affect multiple parameter values using all kinds of combinations of those parameter values in the RelationalExpression/Operator tree. 

Example: Mass parameter should be lower than 100 AND peak_power parameter should be lower than 10 as a Parameteric Constraint.
