### ISSUE TITLE
Connect and open button not active

### ISSUE THREAD

**Issue by jaimecarajunior** [STARIONGROUP/COMET-IME-Community-Edition#1344]
### Description
The button to connect is not becoming active as I type in my password (pic attached).
What could be causing that?

![Screenshot 2024-06-06 170740](https://github.com/STARIONGROUP/COMET-IME-Community-Edition/assets/172033756/039a50cd-48c3-48ba-a7f0-1412b6cb63ed)

**Comment by lxatstariongroup** [comment]
@jaimecarajunior Seems like everything is filled in, so it should be enabled.
My best guess is that you typed in "Edu Server" by hand because you know it should be present in the dropdown of the Source Address inputbox. That does not work, because the server url that might be "behind" that name is not selected automatically, even if the Value in the input box  matches a saved URI.
In general, there should be a url to the server in the input box, or you need to select a saved value by selecting it from the dropdown that you can open using the down-arrow at the right of the Source Address box.
Please let me know if this helps.

**Comment by samatstariongroup** [comment]
@jaimecarajunior did this resolve your issue?

**Comment by jaimecarajunior** [comment]
Thank you for your input, @lxatstariongroup. But that wasn't the case. I did select the name from the dropdown box, exactly because I I had saved the server address under that name. @samatstariongroup, it did not resolve my issue. 
The problem was solved by the It team working on my side.
